android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
android.aarTransform.ignoreMinCompileSdk=true
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
